version: '3'

services:
  app:
    image: nofrialdi/our-backend-warteg
    container_name: our-backend-warteg
    build: .
    ports:
      - 4000:4000
    env_file:
      - .env
    restart: always
    depends_on: [database]

  database:
    image: postgres:alpine
    container_name: our-backend-warteg-database
    hostname: database
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    restart: always

volumes:
  postgres:
